[package]
name = "api"
version = "0.1.0"
authors = ["Mattias de los Rios Rogers <delosrogers@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
mongodb = "0.3.11"
rocket = "0.4.6"
dotenv = "0.13.0"
r2d2 = "0.8.3"
r2d2-mongodb = "*"
rocket_codegen = "0.4"
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
serde_json = "1"


[dependencies.rocket_contrib]
default-features = false
features = ["json"]
version = "0.4"